spring:
  application:
    name: config-service

  profiles:
    active: dev, native

  cloud:
    config:
      server:
        git:
          uri: https://github.com/MMICHIELI/incx.git
        native:
          search-locations: classpath:/config/{profile}